---
title: "ggplot2"
author: "Jan-Philipp Kolb"
date: "04/25/2015"
output: ioslides_presentation
---

```{r,message=F,echo=F}
# setwd("C:/Users/Kolb/Documents/GitHub/RVisualisation/slides")
ca <- T
```


## library ggplot2

- The basic intro on youtube is [here](https://www.youtube.com/watch?v=HeqHMM4ziXA)

```{r,cache=ca,warning=F}
library(ggplot2)
data(mpg)
qplot(displ,hwy,data=mpg)
```


## With color

```{r,cache=ca}
qplot(displ,hwy,data=mpg,color=drv)
```

## Add a smoother

```{r,cache=ca}
qplot(displ,hwy,data=mpg,geom=c("point","smooth"))
```

## facets variable

```{r,cache=ca}
qplot(displ,hwy,data=mpg,facets=.~drv)
```


## Example [geom_abline](http://docs.ggplot2.org/current/geom_abline.html)

```{r,cache=ca}
p <- qplot(wt, mpg, data = mtcars)
p + geom_abline(intercept = 20)
```

## Example geom_line - preparing data

```{r,cache=ca}
mry <- do.call(rbind, by(movies, round(movies$rating), function(df) {
  nums <- tapply(df$length, df$year, length)
  data.frame(rating=round(df$rating[1]), 
             year = as.numeric(names(nums)), 
             number=as.vector(nums))
}))
```


## Example geom_line

```{r,cache=ca}
p <- ggplot(mry, aes(x=year, y=number, group=rating))
p + geom_line()
```

## Example geom_line

```{r,cache=ca}
# Add aesthetic mappings
p + geom_line(aes(size = rating))
```

## Example geom_line

```{r,cache=ca}
p + geom_line(aes(colour = rating))
```


## Example geom.path

```{r,cache=ca}
library(plyr)
myear <- ddply(movies, .(year), colwise(mean, .(length, rating)))
p <- ggplot(myear, aes(length, rating))
p + geom_path()
```

## Example geom.segment

```{r,cache=T}
library(grid) 
df <- data.frame(x=runif(10),y=runif(10),dx=rnorm(10),dy=rnorm(10))
ggplot(data=df, aes(x=x, y=y)) + geom_segment(aes(xend=x+dx, yend=y+dy), arrow = arrow(length = unit(0.3,"cm")))
```


## Links

- [Competition with ggplot2](http://blog.revolutionanalytics.com/2010/09/competition-data-visualization-with-ggplot2.html)